"""updated Route model

Revision ID: 0a13cf0c2da6
Revises: 26e0c8fda6ff
Create Date: 2023-07-07 12:38:57.315475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a13cf0c2da6'
down_revision = '26e0c8fda6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
