"""updated Mountain model

Revision ID: 26e0c8fda6ff
Revises: e5b914b50c18
Create Date: 2023-07-07 12:01:16.421593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e0c8fda6ff'
down_revision = 'e5b914b50c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mountains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mountains', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
